/**
 * Raw seed catalogue. Category/subcategory/collection are referenced by slug
 * and resolved to ObjectIds in seed.ts. Images use deterministic placeholder
 * URLs (picsum) so the store looks populated out of the box — replace with real
 * Cloudinary assets in production.
 */
export interface SeedProduct {
  name: string;
  sku: string;
  price: number;
  discountPercent: number;
  stock: number;
  material: string;
  metalType: string;
  stoneType?: string;
  weightGrams: number;
  dimensions?: string;
  sizes?: string[];
  occasion: string[];
  tags: string[];
  categorySlug: string;
  subcategorySlug?: string;
  collectionKeys: string[];
  shortDescription: string;
  description: string;
  isFeatured?: boolean;
  isNewArrival?: boolean;
  salesCount?: number;
}

export const seedProducts: SeedProduct[] = [
  {
    name: 'Traditional Kundan Bridal Necklace',
    sku: 'AUR-NK-001',
    price: 48500,
    discountPercent: 10,
    stock: 8,
    material: 'Kundan',
    metalType: 'Gold-plated',
    stoneType: 'Kundan',
    weightGrams: 92,
    dimensions: '22 cm length',
    occasion: ['Bridal', 'Wedding'],
    tags: ['kundan', 'bridal', 'necklace', 'statement'],
    categorySlug: 'necklaces',
    collectionKeys: ['bridal', 'royal'],
    shortDescription: 'An heirloom-worthy Kundan necklace set in gold-plated silver.',
    description:
      'A regal bridal centrepiece, this Kundan necklace is hand-set with uncut stones in the centuries-old jadau tradition. Each polished Kundan is framed in gold-plated silver and finished with a cascade of pearls, designed to anchor a bridal ensemble with quiet grandeur.',
    isFeatured: true,
    salesCount: 34,
  },
  {
    name: 'Polki Diamond Choker',
    sku: 'AUR-NK-002',
    price: 62000,
    discountPercent: 5,
    stock: 5,
    material: 'Polki',
    metalType: '22K Gold',
    stoneType: 'Polki Diamond',
    weightGrams: 78,
    dimensions: '16 cm choker',
    occasion: ['Bridal', 'Festive'],
    tags: ['polki', 'choker', 'diamond', 'bridal'],
    categorySlug: 'necklaces',
    subcategorySlug: 'chokers',
    collectionKeys: ['bridal', 'royal'],
    shortDescription: 'Uncut Polki diamonds in a close-set choker silhouette.',
    description:
      'Close-set uncut Polki diamonds catch the light across this structured choker. Backed in 22K gold with fine enamel meenakari on the reverse, it is a piece meant to be seen from every angle.',
    isFeatured: true,
    salesCount: 21,
  },
  {
    name: 'Temple Gold Lakshmi Pendant',
    sku: 'AUR-NK-003',
    price: 31500,
    discountPercent: 0,
    stock: 12,
    material: 'Gold',
    metalType: '22K Gold',
    weightGrams: 34,
    occasion: ['Festive', 'Temple'],
    tags: ['temple', 'gold', 'pendant', 'lakshmi'],
    categorySlug: 'necklaces',
    collectionKeys: ['festive', 'royal'],
    shortDescription: 'Antique-finish temple pendant depicting Goddess Lakshmi.',
    description:
      'Rooted in South Indian temple jewellery, this antique-finish pendant depicts Goddess Lakshmi framed by intricate granulation. A timeless piece for festive and auspicious occasions.',
    salesCount: 18,
  },
  {
    name: 'Meenakari Peacock Necklace',
    sku: 'AUR-NK-004',
    price: 27800,
    discountPercent: 15,
    stock: 10,
    material: 'Meenakari',
    metalType: 'Gold-plated',
    stoneType: 'Kundan',
    weightGrams: 64,
    occasion: ['Festive', 'Party'],
    tags: ['meenakari', 'peacock', 'colourful', 'necklace'],
    categorySlug: 'necklaces',
    collectionKeys: ['festive'],
    shortDescription: 'Hand-painted meenakari peacock motifs in jewel tones.',
    description:
      'The peacock — a recurring muse in Indian craft — is rendered here in vivid hand-painted meenakari enamel. Ruby and emerald tones are set against gold-plated detailing for a piece full of festive colour.',
    isNewArrival: true,
    salesCount: 12,
  },
  {
    name: 'Pearl Rani Haar',
    sku: 'AUR-NK-005',
    price: 39900,
    discountPercent: 8,
    stock: 6,
    material: 'Pearl',
    metalType: 'Gold-plated',
    stoneType: 'Pearl',
    weightGrams: 110,
    dimensions: 'Long, layered',
    occasion: ['Bridal', 'Wedding'],
    tags: ['pearl', 'rani-haar', 'long', 'bridal'],
    categorySlug: 'necklaces',
    collectionKeys: ['bridal', 'royal'],
    shortDescription: 'A layered long haar strung with lustrous freshwater pearls.',
    description:
      'A layered rani haar strung with graded freshwater pearls and punctuated by Kundan-set motifs. Its length and drape make it a statement of understated royalty.',
    salesCount: 9,
  },
  {
    name: 'Antique Gold Jhumka Earrings',
    sku: 'AUR-ER-001',
    price: 18500,
    discountPercent: 0,
    stock: 20,
    material: 'Gold',
    metalType: 'Gold-plated',
    stoneType: 'Pearl',
    weightGrams: 28,
    occasion: ['Festive', 'Party'],
    tags: ['jhumka', 'antique', 'gold', 'earrings'],
    categorySlug: 'earrings',
    subcategorySlug: 'jhumkas',
    collectionKeys: ['festive', 'everyday'],
    shortDescription: 'Classic dome jhumkas with a delicate pearl fringe.',
    description:
      'The jhumka, reimagined with an antique gold finish and a soft fringe of seed pearls. Balanced in weight for all-evening wear, these are the earrings you will reach for again and again.',
    isFeatured: true,
    salesCount: 41,
  },
  {
    name: 'Polki Chandbali Earrings',
    sku: 'AUR-ER-002',
    price: 29500,
    discountPercent: 10,
    stock: 14,
    material: 'Polki',
    metalType: '22K Gold',
    stoneType: 'Polki Diamond',
    weightGrams: 22,
    occasion: ['Bridal', 'Festive'],
    tags: ['chandbali', 'polki', 'earrings', 'bridal'],
    categorySlug: 'earrings',
    collectionKeys: ['bridal', 'festive'],
    shortDescription: 'Crescent chandbalis set with uncut Polki diamonds.',
    description:
      'Inspired by the moon, these crescent chandbalis are tiered with uncut Polki diamonds and finished with a pearl drop. A graceful pairing for bridal and festive occasions alike.',
    isNewArrival: true,
    salesCount: 16,
  },
  {
    name: 'Emerald Drop Stud Earrings',
    sku: 'AUR-ER-003',
    price: 22400,
    discountPercent: 0,
    stock: 18,
    material: 'Gold',
    metalType: '18K Gold',
    stoneType: 'Emerald',
    weightGrams: 9,
    occasion: ['Everyday', 'Office'],
    tags: ['emerald', 'stud', 'minimal', 'earrings'],
    categorySlug: 'earrings',
    subcategorySlug: 'studs',
    collectionKeys: ['everyday', 'minimal'],
    shortDescription: 'A single emerald drop beneath a diamond-accent stud.',
    description:
      'Understated and versatile, these studs pair a brilliant-cut accent with a single emerald drop in 18K gold. Refined enough for the office, elegant enough for the evening.',
    salesCount: 27,
  },
  {
    name: 'Silver Oxidised Jhumka',
    sku: 'AUR-ER-004',
    price: 3200,
    discountPercent: 12,
    stock: 40,
    material: 'Silver',
    metalType: 'Oxidised Silver',
    weightGrams: 18,
    occasion: ['Everyday', 'Casual'],
    tags: ['silver', 'oxidised', 'jhumka', 'boho'],
    categorySlug: 'silver-jewellery',
    collectionKeys: ['everyday', 'minimal'],
    shortDescription: 'Boho oxidised silver jhumkas for everyday character.',
    description:
      'Hand-finished in oxidised silver, these lightweight jhumkas carry tribal-inspired detailing. An easy, characterful choice for daily wear.',
    salesCount: 33,
  },
  {
    name: 'Diamond Halo Ring',
    sku: 'AUR-RG-001',
    price: 54000,
    discountPercent: 5,
    stock: 7,
    material: 'Diamond',
    metalType: '18K White Gold',
    stoneType: 'Diamond',
    weightGrams: 6,
    sizes: ['12', '14', '16', '18'],
    occasion: ['Engagement', 'Anniversary'],
    tags: ['diamond', 'halo', 'ring', 'solitaire'],
    categorySlug: 'rings',
    collectionKeys: ['minimal', 'royal'],
    shortDescription: 'A brilliant solitaire framed by a halo of pavé diamonds.',
    description:
      'A classic halo setting in 18K white gold, with a brilliant-cut centre stone encircled by pavé diamonds. A ring designed for the moments that matter most.',
    isFeatured: true,
    salesCount: 15,
  },
  {
    name: 'Kundan Cocktail Ring',
    sku: 'AUR-RG-002',
    price: 12800,
    discountPercent: 0,
    stock: 22,
    material: 'Kundan',
    metalType: 'Gold-plated',
    stoneType: 'Kundan',
    weightGrams: 8,
    sizes: ['12', '14', '16', '18'],
    occasion: ['Party', 'Festive'],
    tags: ['kundan', 'cocktail', 'ring', 'statement'],
    categorySlug: 'rings',
    collectionKeys: ['festive'],
    shortDescription: 'An oversized Kundan statement ring for festive dressing.',
    description:
      'A bold cocktail ring with a cluster of Kundan stones set in gold-plated silver. Made to be noticed at every celebration.',
    isNewArrival: true,
    salesCount: 11,
  },
  {
    name: 'Minimal Gold Band',
    sku: 'AUR-RG-003',
    price: 15600,
    discountPercent: 0,
    stock: 30,
    material: 'Gold',
    metalType: '18K Gold',
    weightGrams: 4,
    sizes: ['10', '12', '14', '16', '18', '20'],
    occasion: ['Everyday', 'Office'],
    tags: ['gold', 'band', 'minimal', 'stackable'],
    categorySlug: 'rings',
    collectionKeys: ['everyday', 'minimal'],
    shortDescription: 'A slim 18K gold band, perfect for stacking.',
    description:
      'A slim, softly rounded 18K gold band that wears beautifully on its own or stacked. The quiet essential of a considered jewellery wardrobe.',
    salesCount: 29,
  },
  {
    name: 'Meenakari Kada Bangles (Pair)',
    sku: 'AUR-BG-001',
    price: 21500,
    discountPercent: 10,
    stock: 16,
    material: 'Meenakari',
    metalType: 'Gold-plated',
    stoneType: 'Kundan',
    weightGrams: 86,
    sizes: ['2.4', '2.6', '2.8'],
    occasion: ['Festive', 'Wedding'],
    tags: ['meenakari', 'kada', 'bangles', 'pair'],
    categorySlug: 'bangles',
    collectionKeys: ['festive', 'bridal'],
    shortDescription: 'A pair of broad kada bangles with meenakari enamel.',
    description:
      'A matched pair of broad kada bangles, each hand-painted with meenakari enamel and set with Kundan accents. Sold as a pair to frame both wrists.',
    isFeatured: true,
    salesCount: 19,
  },
  {
    name: 'Gold Filigree Bangles Set',
    sku: 'AUR-BG-002',
    price: 34800,
    discountPercent: 6,
    stock: 9,
    material: 'Gold',
    metalType: '22K Gold',
    weightGrams: 120,
    sizes: ['2.4', '2.6', '2.8'],
    occasion: ['Wedding', 'Festive'],
    tags: ['gold', 'filigree', 'bangles', 'set'],
    categorySlug: 'bangles',
    collectionKeys: ['royal', 'festive'],
    shortDescription: 'A set of four filigree bangles in 22K gold.',
    description:
      'Fine filigree work traces each of these four 22K gold bangles. Worn together, they create a soft, resonant stack that speaks of traditional craftsmanship.',
    salesCount: 8,
  },
  {
    name: 'Oxidised Silver Cuff',
    sku: 'AUR-BG-003',
    price: 4600,
    discountPercent: 0,
    stock: 35,
    material: 'Silver',
    metalType: 'Oxidised Silver',
    weightGrams: 42,
    sizes: ['Free'],
    occasion: ['Everyday', 'Casual'],
    tags: ['silver', 'cuff', 'oxidised', 'boho'],
    categorySlug: 'silver-jewellery',
    collectionKeys: ['everyday', 'minimal'],
    shortDescription: 'An adjustable oxidised silver cuff with tribal motifs.',
    description:
      'An open, adjustable cuff in oxidised silver, engraved with tribal-inspired motifs. A striking everyday statement that pairs with both Indian and Western wear.',
    salesCount: 22,
  },
  {
    name: 'Diamond Tennis Bracelet',
    sku: 'AUR-BR-001',
    price: 46500,
    discountPercent: 5,
    stock: 6,
    material: 'Diamond',
    metalType: '18K White Gold',
    stoneType: 'Diamond',
    weightGrams: 16,
    sizes: ['Free'],
    occasion: ['Anniversary', 'Party'],
    tags: ['diamond', 'tennis', 'bracelet', 'luxury'],
    categorySlug: 'bracelets',
    collectionKeys: ['royal', 'minimal'],
    shortDescription: 'A continuous line of brilliant-cut diamonds in white gold.',
    description:
      'A timeless tennis bracelet, set with a continuous line of matched brilliant-cut diamonds in 18K white gold. Refined luxury for the wrist.',
    isFeatured: true,
    salesCount: 10,
  },
  {
    name: 'Rose Gold Charm Bracelet',
    sku: 'AUR-BR-002',
    price: 13200,
    discountPercent: 0,
    stock: 24,
    material: 'Gold',
    metalType: '18K Rose Gold',
    stoneType: 'Cubic Zirconia',
    weightGrams: 12,
    sizes: ['Free'],
    occasion: ['Everyday', 'Gift'],
    tags: ['rose-gold', 'charm', 'bracelet', 'dainty'],
    categorySlug: 'bracelets',
    collectionKeys: ['everyday', 'minimal'],
    shortDescription: 'A dainty rose gold bracelet with delicate charms.',
    description:
      'A delicate rose gold chain hung with fine charms and a scatter of cubic zirconia. A thoughtful, wearable gift for everyday elegance.',
    isNewArrival: true,
    salesCount: 20,
  },
  {
    name: 'Royal Kundan Bridal Set',
    sku: 'AUR-ST-001',
    price: 89500,
    discountPercent: 8,
    stock: 4,
    material: 'Kundan',
    metalType: 'Gold-plated',
    stoneType: 'Kundan',
    weightGrams: 260,
    occasion: ['Bridal', 'Wedding'],
    tags: ['kundan', 'bridal-set', 'necklace', 'earrings', 'maang-tikka'],
    categorySlug: 'bridal-jewellery',
    collectionKeys: ['bridal', 'royal'],
    shortDescription: 'Complete Kundan bridal set: necklace, earrings & maang tikka.',
    description:
      'The complete bridal statement — a Kundan necklace, matching chandbali earrings, and a maang tikka, all set with uncut stones and pearl detailing. Presented in a keepsake box.',
    isFeatured: true,
    salesCount: 7,
  },
  {
    name: 'Polki Bridal Choker Set',
    sku: 'AUR-ST-002',
    price: 96000,
    discountPercent: 6,
    stock: 3,
    material: 'Polki',
    metalType: '22K Gold',
    stoneType: 'Polki Diamond',
    weightGrams: 240,
    occasion: ['Bridal', 'Wedding'],
    tags: ['polki', 'bridal-set', 'choker', 'diamond'],
    categorySlug: 'bridal-jewellery',
    collectionKeys: ['bridal', 'royal'],
    shortDescription: 'Polki choker with matching earrings for the modern bride.',
    description:
      'A Polki choker paired with statement earrings, set in 22K gold with meenakari reverse. Designed for the bride who wants heritage craft with a contemporary silhouette.',
    salesCount: 5,
  },
  {
    name: 'Everyday Gold Chain Pendant',
    sku: 'AUR-NK-006',
    price: 16800,
    discountPercent: 0,
    stock: 28,
    material: 'Gold',
    metalType: '18K Gold',
    stoneType: 'Diamond',
    weightGrams: 7,
    occasion: ['Everyday', 'Office'],
    tags: ['gold', 'chain', 'pendant', 'minimal'],
    categorySlug: 'gold-jewellery',
    collectionKeys: ['everyday', 'minimal'],
    shortDescription: 'A fine gold chain with a single diamond-accent pendant.',
    description:
      'A whisper-fine 18K gold chain suspending a single diamond-accent pendant. The kind of piece you fasten once and never take off.',
    salesCount: 31,
  },
  {
    name: 'Jadau Maang Tikka',
    sku: 'AUR-AC-001',
    price: 14500,
    discountPercent: 0,
    stock: 15,
    material: 'Kundan',
    metalType: 'Gold-plated',
    stoneType: 'Kundan',
    weightGrams: 20,
    occasion: ['Bridal', 'Festive'],
    tags: ['jadau', 'maang-tikka', 'kundan', 'bridal'],
    categorySlug: 'bridal-jewellery',
    collectionKeys: ['bridal', 'festive'],
    shortDescription: 'A jadau maang tikka to complete the bridal look.',
    description:
      'A jadau maang tikka set with Kundan stones and a pearl drop, crafted to sit gracefully along the hair parting. The finishing note of a bridal ensemble.',
    isNewArrival: true,
    salesCount: 6,
  },
  {
    name: 'Emerald Statement Necklace',
    sku: 'AUR-NK-007',
    price: 58000,
    discountPercent: 7,
    stock: 5,
    material: 'Gold',
    metalType: '22K Gold',
    stoneType: 'Emerald',
    weightGrams: 130,
    occasion: ['Festive', 'Party'],
    tags: ['emerald', 'statement', 'necklace', 'royal'],
    categorySlug: 'necklaces',
    collectionKeys: ['royal', 'festive'],
    shortDescription: 'Cabochon emeralds strung on a 22K gold necklace.',
    description:
      'Rich cabochon emeralds are strung along a 22K gold necklace, interspersed with Polki accents. A regal piece with depth of colour and presence.',
    salesCount: 9,
  },
  {
    name: 'Minimal Diamond Solitaire Pendant',
    sku: 'AUR-NK-008',
    price: 33500,
    discountPercent: 0,
    stock: 17,
    material: 'Diamond',
    metalType: '18K White Gold',
    stoneType: 'Diamond',
    weightGrams: 5,
    occasion: ['Everyday', 'Gift'],
    tags: ['diamond', 'solitaire', 'pendant', 'minimal'],
    categorySlug: 'gold-jewellery',
    collectionKeys: ['minimal', 'everyday'],
    shortDescription: 'A single solitaire diamond on a fine white gold chain.',
    description:
      'A single brilliant-cut solitaire suspended on a fine 18K white gold chain. Pure, luminous, and endlessly wearable.',
    salesCount: 24,
  },
  {
    name: 'Festive Gold Jhumka Set',
    sku: 'AUR-ER-005',
    price: 26400,
    discountPercent: 10,
    stock: 13,
    material: 'Gold',
    metalType: '22K Gold',
    stoneType: 'Ruby',
    weightGrams: 30,
    occasion: ['Festive', 'Wedding'],
    tags: ['gold', 'jhumka', 'ruby', 'festive'],
    categorySlug: 'earrings',
    subcategorySlug: 'jhumkas',
    collectionKeys: ['festive', 'royal'],
    shortDescription: 'Ruby-accented 22K gold jhumkas for festive occasions.',
    description:
      'Traditional 22K gold jhumkas accented with rubies and a fine pearl fringe. A festive classic with the weight and warmth of real gold.',
    salesCount: 14,
  },
  {
    name: 'Silver Temple Anklet (Pair)',
    sku: 'AUR-AC-002',
    price: 5400,
    discountPercent: 0,
    stock: 26,
    material: 'Silver',
    metalType: 'Sterling Silver',
    weightGrams: 60,
    sizes: ['Free'],
    occasion: ['Everyday', 'Festive'],
    tags: ['silver', 'anklet', 'payal', 'temple'],
    categorySlug: 'silver-jewellery',
    collectionKeys: ['everyday', 'festive'],
    shortDescription: 'A pair of sterling silver anklets with temple charms.',
    description:
      'A pair of sterling silver anklets (payal) hung with tiny temple bells and charms. Traditional, playful, and made for everyday grace.',
    salesCount: 17,
  },
  {
    name: 'Pearl Stud Earrings',
    sku: 'AUR-ER-006',
    price: 8900,
    discountPercent: 0,
    stock: 32,
    material: 'Pearl',
    metalType: '18K Gold',
    stoneType: 'Pearl',
    weightGrams: 6,
    occasion: ['Everyday', 'Office'],
    tags: ['pearl', 'stud', 'minimal', 'classic'],
    categorySlug: 'earrings',
    subcategorySlug: 'studs',
    collectionKeys: ['everyday', 'minimal'],
    shortDescription: 'Timeless freshwater pearl studs set in 18K gold.',
    description:
      'A single lustrous freshwater pearl set in 18K gold. The most versatile earring you will own — quietly perfect for every day.',
    salesCount: 38,
  },
  {
    name: 'Kundan Layered Long Necklace',
    sku: 'AUR-NK-009',
    price: 44200,
    discountPercent: 12,
    stock: 7,
    material: 'Kundan',
    metalType: 'Gold-plated',
    stoneType: 'Kundan',
    weightGrams: 140,
    occasion: ['Wedding', 'Festive'],
    tags: ['kundan', 'layered', 'long', 'necklace'],
    categorySlug: 'necklaces',
    collectionKeys: ['bridal', 'festive'],
    shortDescription: 'A layered long Kundan necklace with pearl drops.',
    description:
      'A layered long necklace of Kundan motifs interspersed with pearl drops, designed to drape elegantly over festive and bridal wear.',
    isNewArrival: true,
    salesCount: 8,
  },
  {
    name: 'Rose Gold Solitaire Ring',
    sku: 'AUR-RG-004',
    price: 41500,
    discountPercent: 5,
    stock: 9,
    material: 'Diamond',
    metalType: '18K Rose Gold',
    stoneType: 'Diamond',
    weightGrams: 5,
    sizes: ['12', '14', '16', '18'],
    occasion: ['Engagement', 'Gift'],
    tags: ['rose-gold', 'solitaire', 'ring', 'diamond'],
    categorySlug: 'rings',
    collectionKeys: ['minimal', 'royal'],
    shortDescription: 'A brilliant solitaire set in warm 18K rose gold.',
    description:
      'A brilliant-cut solitaire raised in a fine six-prong setting of 18K rose gold. Warm, romantic, and beautifully proportioned.',
    salesCount: 12,
  },
  {
    name: 'Antique Gold Chooda Bangles',
    sku: 'AUR-BG-004',
    price: 28900,
    discountPercent: 0,
    stock: 11,
    material: 'Gold',
    metalType: 'Gold-plated',
    stoneType: 'Kundan',
    weightGrams: 150,
    sizes: ['2.4', '2.6', '2.8'],
    occasion: ['Bridal', 'Wedding'],
    tags: ['antique', 'chooda', 'bangles', 'bridal'],
    categorySlug: 'bangles',
    collectionKeys: ['bridal', 'royal'],
    shortDescription: 'A bridal chooda of antique-finish Kundan bangles.',
    description:
      'A set of antique-finish bangles forming a bridal chooda, each set with Kundan and finished with fine detailing. A traditional wrist stack for the wedding day.',
    salesCount: 6,
  },
];
